name: Android CI

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '.idea/**'

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }} && success() && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          java-package: jdk
          distribution: 'temurin'

      - run: ./gradlew app:assemble

      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: app/build/outputs/apk/release

      - uses: actions/upload-artifact@v3
        with:
          name: debug
          path: app/build/outputs/apk/debug