name: Pull Request Checker

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Pull request check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.1'
      - name: Prepare Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          java-package: jdk
          distribution: 'temurin'
          cache: 'gradle'
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:assembleRelease
          echo "DEBUG_APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV
          echo "RELEASE_APK_FILE=$(find app/build/outputs/apk/release -name '*.apk')" >> $GITHUB_ENV
      - name: Upload Artifacts(debug)
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.DEBUG_APK_FILE }}
          name: app-debug
      - name: Upload Artifacts(release)
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.RELEASE_APK_FILE }}
          name: app-release